"""Initial migration

Revision ID: def96157cef9
Revises: 
Create Date: 2026-06-16 23:02:17.354378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def96157cef9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('resource_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('resource_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('resource_id'),
    sa.UniqueConstraint('resource_name')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('access_rules',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_read_own', sa.Boolean(), nullable=False),
    sa.Column('can_read_all', sa.Boolean(), nullable=False),
    sa.Column('can_update_own', sa.Boolean(), nullable=False),
    sa.Column('can_update_all', sa.Boolean(), nullable=False),
    sa.Column('can_delete_own', sa.Boolean(), nullable=False),
    sa.Column('can_delete_all', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'resource_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('patronymic', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('access_rules')
    op.drop_table('roles')
    op.drop_table('resources')
    # ### end Alembic commands ###
